### ISSUE TITLE
Add search capability

### ISSUE THREAD

**Issue by ohadschn** [4tal/LinksForIsrael#103]
Some options:
https://learn.cloudcannon.com/jekyll-search/

Motivation: 
1. https://github.com/4tal/LinksForIsrael/issues/93#issuecomment-1759477318 (descriptions hovers aren't searched)
2. https://github.com/4tal/LinksForIsrael/issues/77 (once we have separate pages, browser search won't be enough anyway)

**Comment by splintor** [comment]
Wasn't this resolved in #150

**Comment by oriharel** [comment]
> Wasn't this resolved in #150 ?
Yes. thanks
