### ISSUE TITLE
Add subsection in https://4tal.github.io/ConnectPortal/docs/contribute on how to setup the environment

### ISSUE THREAD

**Issue by 4tal** [4tal/LinksForIsrael#11]
It should be in English Right To Left

**Comment by ohadschn** [comment]
@4tal I don't follow, it already has a section for it, and I'm not sure what you meant in the other issue about having it in hebrew and linking a subpage (also, why 2 separate issues)?

**Comment by 4tal** [comment]
Not Relevant
