### ISSUE TITLE
Change the https://4tal.github.io/ConnectPortal/docs/contribute page to Hebrew

### ISSUE THREAD

**Issue by 4tal** [4tal/LinksForIsrael#12]
And link the subpage from 
#11

**Comment by liranprof** [comment]
Press on  menu button vertical three dots and translate to  Hebrew

**Comment by ohadschn** [comment]
I disagree, such technical instructions should remain in English (any potential contributor would have to know it anyway)
However, the text direction should be fixed - currently it's RTL

**Comment by 4tal** [comment]
Not Relevant
