### ISSUE TITLE
Prioritize categories 

### ISSUE THREAD

**Issue by ohadschn** [4tal/LinksForIsrael#120]
I propose something like
1. Donations - consider unifying with Crypto (most generic, anyone can do, can contribute to any cause)
2. War effort (equipment. reserve, self-defense)
3. Families (hosting, food, bereaved, missing persons)
4. Publicity (hasbara) & News/info
5. Mental wellbeing (psychological help, free content)
6. Uncategorized - IMO can be moved to Cyber

**Comment by 4tal** [comment]
Will be update using mix panel


![Image](https://github.com/4tal/LinksForIsrael/assets/6404507/672dd59e-24da-4cd5-b97b-f49c233da641)
