### ISSUE TITLE
Add Israel's main publicity page: https://instagram.com/standwithus?igshid=MzRlODBiNWFlZA==

### ISSUE THREAD

**Issue by ohadschn** [4tal/LinksForIsrael#125]
לעקוב אחרי העמוד הסברה של ישראל.
לעמוד תמיכה של פלסטין יש 3 מיליון עוקבים ולנו אפילו לא 800 אלף!

תעקבו ותשתפו. 🙏🏼🇮🇱💙

**Comment by 4tal** [comment]
Done
