### ISSUE TITLE
Add "Lev Ehad" funeral attendance support form: https://wkf.ms/46mj8OG 

### ISSUE THREAD

**Issue by ohadschn** [4tal/LinksForIsrael#134]
אזרחים ואזרחיות יקרים, לצערנו המלחמה גבתה וממשיכה לגבות קורבנות רבים. 
ארגון 'לב אחד' דואג שלא תהיה לוויה ללא נציגים אזרחיים. 
יש צורך במתנדבים רבים. אם יש באפשרותך לקחת חלק בהשתתפות בלוויות, נודה להשתבצותך בלינק הבא

**Comment by 4tal** [comment]
Done
