### ISSUE TITLE
Examine Descriptive Tags

### ISSUE THREAD

**Issue by 4tal** [4tal/LinksForIsrael#14]
Introduce descriptive tags for tasks, initiatives, and projects for at-a-glance understanding.

**Comment by ohadschn** [comment]
@4tal  And possibly more importantly, for filtering

**Comment by bergden-resonai** [comment]
Hi, I'm new to the project - I sampled a bunch of issues and some of them were WIP or even closed (but not marked as closed) - I think if people could self-assign themselves or at least add a label indicating they work on it it'll be easier to navigate

**Comment by bergden-resonai** [comment]
Also some tickets are not defined yet, i.e [here](https://github.com/4tal/LinksForIsrael/issues/19) there's a feature request but the developers don't know exactly what to do or if this is a "Ready to go" ticket
I suggest adding a label for `Spec needed` and `Ready to go` (and maybe even `UI needed`) to help differentiate tickets that require product/UX/UI/developer attention
