### ISSUE TITLE
Suggest solution for file hosting

### ISSUE THREAD

**Issue by 4tal** [4tal/LinksForIsrael#17]
We can link images as information as part of the website. What is the proper solution for community managed images.

**Comment by ohadschn** [comment]
What do you mean by "community managed images"?
Anyway, just add them to the repo (as part of the PR, either manual or generated), then you can reference them normally.
See: https://tomcam.github.io/least-github-pages/adding-images-github-pages-site.html 
In fact that entire site looks like a pretty good resource: https://tomcam.github.io/least-github-pages

**Comment by 4tal** [comment]
Perfect
