### ISSUE TITLE
Add civilian front whatsapp group (hasbara / publicity)

### ISSUE THREAD

**Issue by ohadschn** [4tal/LinksForIsrael#173]
Almost 850 members so probably legit:
חמל מידע החזית האזרחית

היי לכולם!!!
תודה שאתם כאן. תודה שאתם משתפים, תומכים ומתנדבים לקדם את ההסברה הישראלית! 🇮🇱
השם של המיזם הוא The Civilian Front ובעברית, החזית האזרחית.
מדובר בצוות איכותי וערכי של מתנדבים אזרחים שעובדים מסביב לשעון בשביל להלחם בחזית ההסברתית. 

לינק להצטרפות: https://chat.whatsapp.com/LGKPchQGakg4E75XYfEfyS

בהמשך לייעול ההפצה חילקנו את ההסברה לפי פלטפורמות שיהיה לכם נוח❤️

חמל מידע פייסבוק: https://chat.whatsapp.com/DIlLKYyHJWk02AAP85dpSn
חמל מידע אינסטגרם: https://chat.whatsapp.com/BjnPe6nwabqFY8jLxbBtoz
חמל מידע טיקטוק: https://chat.whatsapp.com/Hw7fdndJdYy6TPsDii9o5V
חמל מידע לינקדאין: https://chat.whatsapp.com/K6oQQ519mP37zGRufnLkzt
חמל מידע טוויטר: https://chat.whatsapp.com/Ez1hDNEt0OZF5a9sGgYueO

**Comment by 4tal** [comment]
<img width="690" alt="image" src="https://github.com/4tal/LinksForIsrael/assets/6404507/3876a16e-793b-4f7e-a9ec-82ba3cc711c9">
