### ISSUE TITLE
Add free medical consultation: https://www.hopp.bio/irondoctors

### ISSUE THREAD

**Issue by ohadschn** [4tal/LinksForIsrael#176]
Source: WeHelpIsrael (legit, I had a video call with their admin)
יעוץ רפואי מהיר ללא תשלום למבוטחי כלל הקופות
השירות פעיל בשלב זה בין 16:00-20:00, אך שעות הפעילות יתעדכנו מעת לעת.
לאור מצב החירום בישראל, קהילת "חדר רופאות" בשיתוף עם "שיבא ביונד" ובסיוע חברת קונסיסט ובוגרי 8200, הקימו מוקד רופאים ורופאות שיעמדו לרשותכם בצ'אט בוואטסאפ. הייעוץ ניתן למצבים לא דחופים בתחומים שונים כולל רפואת ילדים, משפחה, נשים ושיניים. 
קישור להתחלת התכתבות בוואטסאפ מופיע בקישור המצורף.

**Comment by 4tal** [comment]
#181
