### ISSUE TITLE
Add linkedin terror supporter index: https://terrorsupporters.vercel.app/

### ISSUE THREAD

**Issue by ohadschn** [4tal/LinksForIsrael#178]
Source: https://www.facebook.com/groups/hitechproblems/permalink/1860792664323114/?mibextid=W9rl1R
Also sampled a few posts, looks legit (if controversial, in the sense that many posts don't actually support Hamas directly)

**Comment by 4tal** [comment]
#180

**Comment by ohadschn** [comment]
Fixed link:
https://github.com/4tal/LinksForIsrael/commit/b5e708a7d2f1d129dab95840e332e3878b47e46b
