### ISSUE TITLE
Add link to https://israel-vs-animals.streamlit.app/

### ISSUE THREAD

**Issue by ohadschn** [4tal/LinksForIsrael#34]
Verified by an MS employee colleague (I actually think it was built by an MS employee too)

> An AI Chatbot that answers any question you have about the Hamas October 7th attack.
> You can ask any question, in any language.
> Please share and help spread the truth.

**Comment by 4tal** [comment]
![Image](https://github.com/4tal/LinksForIsrael/assets/6404507/895b0365-ba1d-4c22-aeea-477fa825f0b8)

I think we can skip it for now
