### ISSUE TITLE
Make it easier to get to our repository on the home page

### ISSUE THREAD

**Issue by 4tal** [4tal/LinksForIsrael#57]

**Comment by chiptus** [comment]
do we want the github link in the top bar? maybe something like this:
![image](https://github.com/4tal/LinksForIsrael/assets/1381655/3f12c80d-ad40-4b97-a195-283783971901)

or 
![image](https://github.com/4tal/LinksForIsrael/assets/1381655/359d8f8e-72c5-4766-ba73-90231191afc2)

and on mobile we can hide the text and just have the two buttons

**Comment by 4tal** [comment]
It was before having Whatsapp link. Considered done
