### ISSUE TITLE
Add link to settlement defense initiative

### ISSUE THREAD

**Issue by ohadschn** [4tal/LinksForIsrael#81]
Verified, I know one of the organizers from my IDF service
מתנהל עכשיו  מבצע מדהים לעזור ליישובים שבצפון/דרום להגן על עצמם.
הפיילוט יפרס עד מחר באחד היישובים בצפון ואנחנו מרכזים רשימה של כל היישובים שבהם קיימת כ״כ (כיתות כוננות/אבטחה) פעילות. 
בקשה תמלאו בטופס המצורף את כל מה שאתם מכירים -   https://forms.gle/JX68hPp8JnGRr1Tz7
אם יש מישהו שאני יכולה לדבר איתו כדי לקבל רשימה מסודרת - ממש אשמח

**Comment by 4tal** [comment]
Not Relevant Anymore


![Image](https://github.com/4tal/LinksForIsrael/assets/6404507/dce33242-25c7-4fd7-92ba-a8de3e1c3f5f)
